#!/bin/bash

function initialize_system() {
  install_basic_packages

  initialize_vim

  initialize_git

  initialize_i3

  initialize_bash

  initialize_tmux

  initialize_node

  install_watchers

  install_terminal

  install_liquidprompt

  # Remove broken symlinks
  clean_symlinks
  echo -e "\nDone!"
}

function initialize_vim() {
  sudo apt install --yes vim

  echo -e "\nSetting symlinks..."
  symlink "${HOME}/.dotfiles/vim/vimrc" "${HOME}/.vimrc"
  symlink "${HOME}/.dotfiles/vim" "${HOME}/.vim"

  vim +PlugInstall +qall
}

function initialize_i3() {
  sudo apt install --yes i3

  symlink "${HOME}/.dotfiles/.Xresources" "${HOME}/.Xresources"

  symlink "${HOME}/.dotfiles/.config" "${HOME}/.config"
}

function initialize_git() {
  sudo apt install --yes git git-extras

  symlink "${HOME}/.dotfiles/git/.gitignore" "${HOME}/.gitignore"
  symlink "${HOME}/.dotfiles/git/.gitconfig" "${HOME}/.gitconfig"
  symlink "${HOME}/.dotfiles/git/.gitmessage" "${HOME}/.gitmessage"
  symlink "${HOME}/.dotfiles/git/.git-templates" "${HOME}/.git-templates"
}

function initialize_bash() {
  symlink "${HOME}/.dotfiles/bash/.bash_profile" "${HOME}/.bash_profile"
  symlink "${HOME}/.dotfiles/bash/.bashrc" "${HOME}/.bashrc"
  symlink "${HOME}/.dotfiles/.startup" "${HOME}/.startup"
}

function initialize_tmux() {
  symlink "${HOME}/.dotfiles/.tmux" "${HOME}/.tmux"
  symlink "${HOME}/.dotfiles/.tmux/tmux.conf" "${HOME}/.tmux.conf"

  wget https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.bash -O /etc/bash_completion.d/tmuxinator.bash
}

function initialize_node() {
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

  nvm install --lts
  nvm use --lts
}

function install_tools() {
  symlink "${HOME}/.dotfiles/bin/*" "/usr/local/bin/*"

  npm install -g @qnzl/lockbox

  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
}

function install_liquidprompt() {
  git clone https://github.com/nojhan/liquidprompt.git ~/.dotfiles/bash/liquidprompt
}

function install_terminal() {
  sudo apt install kitty
}

function install_basic_packages() {
  sudo apt install build-essential feh autojump blueman pass entr silversearcher-ag tmux

  sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
  sudo chmod a+rx /usr/local/bin/youtube-dl
}

function uninstall_dotfiles() {
  rm -rf "$HOME"/.dotfiles
  "$HOME"/.fzf/uninstall
  rm -rf "$HOME"/.fzf
  clean_symlinks
  echo -e "\dotfiles uninstalled"
}

function clean_symlinks() {
  find -L . -maxdepth 1 -type l -exec rm -- {} +
}

function symlink() {
  echo "SYMLINK"
  # If this isnt a symlink
  if [ ! -L "$2" ]; then
    # Backup the file
    mv "$2" "$2.backup" >/dev/null 2>&1

    # Now remove it, dirs too
    rm -rf "$2" >/dev/null 2>&1
  fi

  # If the target is already a symlink
  if [ -L "$2" ]; then
    rm "$2" >/dev/null 2>&1
  fi

  # Create symlink
  sudo ln -s "$1" "$2"
  echo -e "$1 --> $2"
}

initialize_node
