#!/bin/bash

function install_dotfiles() {

  # Liquid prompt
  echo -e "\nInstalling Liquid Prompt"
  rm -rf $HOME/.dotfiles/zsh/liquidprompt
  git clone git@github.com:nojhan/liquidprompt.git $HOME/.dotfiles/zsh/liquidprompt
  symlink "${HOME}/.dotfiles/bash/liquidprompt/liquidpromptrc-dist" "${HOME}/.liquidpromptrc"

  sudo apt-get install git-extras

  # Vim
  echo -e "\nSetting symlinks..."
  symlink "${HOME}/.dotfiles/vim/vimrc" "${HOME}/.vimrc"
  symlink "${HOME}/.dotfiles/vim" "${HOME}/.vim"

  # zsh profile
  symlink "${HOME}/.dotfiles/zsh" "${HOME}/.zsh"
  symlink "${HOME}/.dotfiles/zsh/start_vpn" "${HOME}/.start_vpn"
  symlink "${HOME}/.dotfiles/zsh/profile" "${HOME}/.profile"
  symlink "${HOME}/.dotfiles/zsh/profile" "${HOME}/.zshrc"
  symlink "${HOME}/.dotfiles/zsh/profile" "${HOME}/.zsh_profile"

  # inputrc
  symlink "${HOME}/.dotfiles/zsh/inputrc" "${HOME}/.inputrc"

  # Tmux
  symlink "${HOME}/.dotfiles/tmux/tmux.conf" "${HOME}/.tmux.conf"

  # git
  symlink "${HOME}/.dotfiles/git/.gitconfig" "${HOME}/.gitconfig"
  symlink "${HOME}/.dotfiles/git/.gitmessage" "${HOME}/.gitmessage"
  symlink "${HOME}/.dotfiles/git/.git-templates" "${HOME}/.git-templates"

  # guake
  symlink "${HOME}/.dotfiles/guake/" "${HOME}/.gconf/apps/guake"

  # vpn
  symlink "${HOME}/.dotfiles/security/.openvpn/" "${HOME}/.openvpn"
  ./security/install_pia.zsh

  # Remove broken symlinks
  clean_symlinks
  echo -e "\nDone!"
}

function uninstall_dotfiles() {
  rm -rf $HOME/.dotfiles
  $HOME/.fzf/uninstall
  rm -rf $HOME/.fzf
  clean_symlinks
  echo -e "\dotfiles uninstalled"
}

function clean_symlinks() {
  find -L . -maxdepth 1 -type l -exec rm -- {} +
}

function symlink() {
  # If this isnt a symlink
  if [ ! -L "$2" ]; then
    # Backup the file
    mv "$2" "$2.backup" >/dev/null 2>&1

    # Now remove it, dirs too
    rm -rf "$2" >/dev/null 2>&1
  fi

  # If the target is already a symlink
  if [ -L "$2" ]; then
    rm "$2" >/dev/null 2>&1
  fi

  # Create symlink
  ln -s $1 $2
  echo -e "$1 --> $2"
}

install_dotfiles