#!/bin/bash

function install_dotfiles() {

  # FZF
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install

  # Vim
  echo -e "\nSetting symlinks..."
  symlink "${HOME}/.dotfiles/vim/vimrc" "${HOME}/.vimrc"
  symlink "${HOME}/.dotfiles/vim" "${HOME}/.vim"

  # Bash profile
  SHELL="$(echo ${0} | awk -F"/" '{print $NF}')"
  if [[ $SHELL == "bash" ]]; then
    symlink "${HOME}/.dotfiles/bash" "${HOME}/.bash"
    symlink "${HOME}/.dotfiles/bash/profile" "${HOME}/.profile"
    symlink "${HOME}/.dotfiles/bash/profile" "${HOME}/.bashrc"
    symlink "${HOME}/.dotfiles/bash/profile" "${HOME}/.bash_profile"
  else
    symlink "${HOME}/.dotfiles/zsh" "${HOME}/.zsh"
    symlink "${HOME}/.dotfiles/zsh/profile" "${HOME}/.profile"
    symlink "${HOME}/.dotfiles/zsh/profile" "${HOME}/.zshrc"
    symlink "${HOME}/.dotfiles/zsh/profile" "${HOME}/.zsh_profile"
  fi

  # Liquid prompt
  echo -e "\nInstalling Liquid Prompt for ${SHELL}"
  rm -rf $HOME/.dotfiles/${SHELL}/liquidprompt
  git clone git@github.com:nojhan/liquidprompt.git $HOME/.dotfiles/${SHELL}/liquidprompt
  symlink "${HOME}/.dotfiles/${SHELL}/liquidprompt/liquidpromptrc-dist" "${HOME}/.liquidpromptrc"

  # inputrc
  symlink "${HOME}/.dotfiles/${SHELL}/inputrc" "${HOME}/.inputrc"

  # Tmux
  symlink "${HOME}/.dotfiles/tmux/tmux.conf" "${HOME}/.tmux.conf"

  # Remove broken symlinks
  clean_symlinks
  echo -e "\nDone!"
}

function uninstall_dotfiles() {
  rm -rf $HOME/.dotfiles
  $HOME/.fzf/uninstall
  rm -rf $HOME/.fzf
  clean_symlinks
  echo -e "\dotfiles uninstalled"
}

function clean_symlinks() {
  find -L . -maxdepth 1 -type l -exec rm -- {} +
}

function symlink() {
  # If this isnt a symlink
  if [ ! -L "$2" ]; then
    # Backup the file
    mv "$2" "$2.backup" >/dev/null 2>&1

    # Now remove it, dirs too
    rm -rf "$2" >/dev/null 2>&1
  fi

  # If the target is already a symlink
  if [ -L "$2" ]; then
    rm "$2" >/dev/null 2>&1
  fi

  # Create symlink
  ln -s $1 $2
  echo -e "$1 --> $2"
}
