#!/bin/bash

function moveFiles() {
  TYPE=$1
  FROM_WHERE=$2
  TO_WHERE=$3

  find $2 -maxdepth 1 -type f -iname "$1" | while read f
  do
    mv "$f" $3
  done
}

unneededFiles=()
uneededFolders=()

mkdir -p ~/Downloads/{ISO,GIFs,}

readarray -d '' unneededFolders < <(find ~ -maxdepth 1 -type d -iname "[A-z]*" | ack '(\/home\/[A-z]+\/)(?!Documents|code|Music|Public|Dropbox|Downloads|Videos|Pictures|Desktop|Dump|Android)')

mkdir -p ~/Dump
mkdir -p ~/Dump/Images

for folder in ${unneededFolders[@]}; do
  mv "$folder/*" ~/Dump
done

find ~ -maxdepth 1 -type f -name "*" -not -name ".*" -print0 |
  while IFS= read -r -d '' file; do
    mv "$file" ~/Dump
done

moveFiles "*.gif" ~ ~/Downloads/GIFs
moveFiles "*.iso" ~/Downloads ~/Downloads/ISO
moveFiles "*.gif" ~/Downloads ~/Downloads/GIFs

##################

photos=$(find ~/Downloads -maxdepth 1 -type f \( -name "*jpg" -o -name "*png" -o -name "*PNG" -o -name "*JPG" -o -name "*JPEG" \) | ack '(\/home\/[A-z]+\/Downloads\/(IMG|(20[0-9]{2})).*\.(jpg|JPG|jpeg))')

for photo in $photos; do
  mv "$photo" ~/Dump/Images
done

# Move everything left
moveFiles "*" ~/Downloads ~/Dump
