#!/bin/bash

. "${HOME}/.dotfiles/zsh/start_vpn"

# Autoload include directory
for includeFile in $(find "${HOME}/.dotfiles/zsh/includes" -type f)
do
  . "${includeFile}"
done

EDITOR=vim
TZ=America/New_York
LANG=en_US.UTF-8
HISTFILE="${HOME}/.history"
HISTSIZE=10000

# Auto-enable colors for commands like 'ls'
CLICOLOR=1

# Vim key bindings
set -o vi

export EDITOR TZ LANG HISTFILE HISTSIZE CLICOLOR

# rbenv
if type -p rbenv >/dev/null 2>&1 ; then
  eval "$(rbenv init -)"
fi

# liquid prompt
[[ $- = *i* ]] && source ${HOME}/.dotfiles/zsh/liquidprompt/liquidprompt

# Start ssh-agent, load ssh keys
if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  ssh-add
fi

# Grep colors
export GREP_OPTIONS='--color=auto'

# Update path
export PATH=$HOME/usr/local/sbin:$PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.bpkg/bin:"$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
