#!/bin/bash

. "${HOME}/.dotfiles/install"

# Autoload include directory
for includeFile in $(find "${HOME}/.dotfiles/zsh/includes" -type f)
do
  . "${includeFile}"
done

EDITOR=vim
TZ=America/New_York
LANG=en_US.UTF-8
HISTFILE="${HOME}/.history"
HISTSIZE=10000

# Auto-enable colors for commands like 'ls'
CLICOLOR=1

# Vim key bindings
set -o vi

export EDITOR TZ LANG HISTFILE HISTSIZE CLICOLOR

# Used by bash, unused by mksh
if [ "${0##*/}" = "bash" ] || [ "${0}" = "-bash" ] ; then
  setopt -s expand_aliases
  setopt -s checkwinsize
  HISTFILESIZE=2000
  HISTCONTROL=ignoredups:ignorespace
  export HISTFILESIZE HISTCONTROL
fi

# rbenv
if type -p rbenv >/dev/null 2>&1 ; then
  eval "$(rbenv init -)"
fi

# liquid prompt
source ~/.dotfiles/zsh/liquidprompt/liquidprompt/liquidprompt

# Load a local profile
# [ -r "${HOME}/.localprofile" ] && . "${HOME}/.localprofile"

# Start ssh-agent, load ssh keys
if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  ssh-add
fi

# Grep colors
export GREP_OPTIONS='--color=auto'

# Update path
export PATH=$HOME/usr/local/sbin:$PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.bpkg/bin:"$PATH"
export GOPATH=$HOME/code/pantryplan/API
export GOBIN=$GOPATH/bin

# Better man pages
export PAGER=most

export ANDROID_HOME="$HOME/Android/Sdk"
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
