#!/bin/bash

# Autoload include directory
for includeFile in $(find "${HOME}/.dotfiles/bash/includes" -type f)
do
  . "${includeFile}"
done

EDITOR=vim
TZ=America/New_York
LANG=en_US.UTF-8
HISTFILE="${HOME}/.history"
HISTSIZE=10000

# Auto-enable colors for commands like 'ls'
CLICOLOR=1

# Vim key bindings
set -o vim

export EDITOR TZ LANG HISTFILE HISTSIZE CLICOLOR

# rbenv
if type -p rbenv >/dev/null 2>&1 ; then
  eval "$(rbenv init -)"
fi

# liquid prompt
[[ $- = *i* ]] && source ${HOME}/.dotfiles/bash/liquidprompt/liquidprompt

# Start ssh-agent, load ssh keys
if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  ssh-add
fi

use_color=true

# Update path
export PATH=$HOME/usr/local/sbin:$PATH
export PATH=$HOME/bin:$PATH

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
source ~/.dotfiles/ssh/connect

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
